import type { Metadata } from 'next';
import { Cairo as FontSans } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';

import AuthProvider from '@/auth';
import Navbar from '@/components/Navbar';
import AlertProvider from '@/providers/alertProvider';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ar">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <AuthProvider>
          <AlertProvider>
            {/* @ts-expect-error */}
            <Navbar />
            {children}
          </AlertProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
