import type { Metadata } from "next";
import { Cairo as FontSans } from "next/font/google"
import "./globals.css";
import { cn } from "@/lib/utils";

import getServerAuth from "@/auth/server";
import AuthProvider from "@/auth";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({children}:Readonly<{children: React.ReactNode;}>) {
  await getServerAuth();
  
  return (
    <html lang="ar">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
          <AuthProvider>
            {children}
          </AuthProvider>
          </body>
    </html>
  );
}
